services:
  - type: web
    name: bizuplift-backend
    runtime: node
    plan: free
    rootDir: BizUplift-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: bizuplift-frontend
    runtime: static
    rootDir: BizUplift-main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
